### ISSUE TITLE
find-issues 更新

### ISSUE THREAD

**Issue by xrkffgg** [actions-cool/issues-helper#101]
# 想要一个 

# `find-issues`

查找当前仓库中，创建者是 k ，标题包含 `that` ，内容包含 `this` 的议题列表。

```yml
- name: Find issues
    uses: actions-cool/issues-helper@v2
    with:
      actions: 'find-issues'
      token: ${{ secrets.GITHUB_TOKEN }}
      issue-auth: 'k'
      title-includes: 'that'
      body-includes: 'this'
```

| 参数 | 描述 | 类型 | 必填 |
| -- | -- | -- | -- |
| actions | 操作类型 | string | ✔ |
| token | [token 说明](#token) | string | ✔ |
| issue-auth | 议题创建者，不填时会查询所有 | string | ✖ |
| title-includes | 议题标题包含过滤，不填时无校验 | string | ✖ |
| body-includes | 议题内容包含过滤，不填时无校验 | string | ✖ |
| direction | 返回 `issues` 排序 | string | ✖ |

- 返回 `issues`，格式如下：

```js
[
  {id: 1, auth: 'x', title: 'aaa', body: 'xxx', created: '', updated: ''},
  {id: 2, auth: 'x', title: 'aaa', body: 'xxx', created: '', updated: ''},
]
```

- `direction` 默认为升序，只有设置 `desc` 时，会返回降序
- 返回数组中 `created` `updated`，由所处环境决定，会是 UTC +0

_Originally posted by @MichaelMai2000 in https://github.com/actions-cool/issues-helper/discussions/18#discussioncomment-2015504_
