### ISSUE TITLE
[Feature] Add list-assignees function

### ISSUE THREAD

**Issue by maxdanilov** [actions-cool/issues-helper#113]
### 🥰 需求描述 Description of Requirement

I'd like to request a `list-assignees` function that will return the list of the current issue assignees without changing them.

### 🧐 解决方案 Solution

I was thinking of:
```yaml
jobs:
  list-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: List assigness
        id: list-assignees
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'list-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
     - name: Print assignees
        id: print-assignees
        run: |
          echo "The current assignees are: ${{ steps.list-assignees.outputs.assignees }}"
```

This would print something like:

> The current assignees are: xx1,xx2
