### ISSUE TITLE
[Feature] New function check-comment

### ISSUE THREAD

**Issue by pansong291** [actions-cool/issues-helper#128]
### 🥰 需求描述 Description of Requirement
```yml
name: Check Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    steps:
      - id: check-comment
        name: check-comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body-includes: 'x1,x2'
```
```
if: steps.check-comment.outputs.check-result == 'true'
```

### 🧐 解决方案 Solution
https://docs.github.com/en/rest/issues/comments#get-an-issue-comment
