### ISSUE TITLE
[Feature] add the currently logged in github user among static users as assignees

### ISSUE THREAD

**Issue by PeterDeathBredon** [actions-cool/issues-helper#160]
### 🥰 需求描述 

whenever we create a new issue we want one static user added as assignee and the currently logged in user, too

### 🧐 解决方案 Solution

This is what I tried, but it only adds the static "urapadmin" as assignee

```
name: Add Assigness

on:
  issues:
    types: [opened]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'urapadmin,${{ github.actor }}'
          random-to: 1

```
Any suggestions?

**Comment by xrkffgg** [comment]
Try

```yml
name: Add Assigness

on:
  issues:
    types: [opened]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: urapadmin, ${{ github.actor }}
```
