### ISSUE TITLE
[Question] For `label` property how to represent multiple labels?

### ISSUE THREAD

**Issue by melloware** [actions-cool/issues-helper#187]
IF I have this...

```
labels: "Resolution: Cannot Replicate Status: Needs Reproducer"
```

How does your code know to do `Resolution: Cannot Replicate` AND `Status: Needs Reproducer` should it be comma separated?

**Comment by xrkffgg** [comment]
`Resolution: Cannot Replicate,Status: Needs Reproducer`

**Comment by melloware** [comment]
Yeah that did not seem to work i wonder if it didn't like the spaces?  So I broke it into two separate queries and that works.

```yaml
steps:
      - name: Cannot Replicate
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          labels: "Resolution: Cannot Replicate"
          inactive-day: 20
      - name: Needs Reproducer
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          labels: "Status: Needs Reproducer"
          inactive-day: 20
```
