### ISSUE TITLE
[BUG] Inaccurate Warning Message

### ISSUE THREAD

**Issue by milldr** [actions-cool/issues-helper#196]
### 🐛 Bug description

When using the `actions: 'close-issues'` or `actions: find-issues` inputs, we should not provide an issue number. However when we don't, we get this warning message:

```console
--
[🎃 AC] 'issue-number' is missing or this action not needed yet!
```

Otherwise the action is working as expected!

### 🏞  Desired result

We should not see this warning message if our implementation is correct

### 🚑 Other information

Here is my usage for examples:

```yaml
      - name: Find all issues
        id: issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ github.token }}
          labels: 'foobar'
          issue-state: 'open'
```

and

```yaml
      - name: Close all matching issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ github.token }}
          labels: 'foobar'
```
