### ISSUE TITLE
[Feature] Update if not Create issue

### ISSUE THREAD

**Issue by KingBain** [actions-cool/issues-helper#200]
I would love to be able to use one step to update an issue, if the issue doesnt exist. create it .

This works but ...3 steps 
```
      - name: Find existing drift issue
        id: find_drift_report
        uses: actions-cool/issues-helper@v3
        with:
          actions: find-issues
          title-includes: 'Terraform Drift Report'
          labels: 'terraform,drift,alert'

      - name: Create drift issue if missing
        if: steps.find_drift_report.outputs.issues == '[]'
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-issue
          title: "Terraform Drift Report"
          labels: terraform,drift,alert
          body: |
            yada yada
          
      - name: Update drift issue if present
        if: steps.find_drift_report.outputs.issues != '[]'
        uses: actions-cool/issues-helper@v3
        with:
          actions: update-issue
          issue-number: ${{ fromJSON(steps.find_drift_report.outputs.issues)[0].number }}
          update-mode: append
          body: |
            yada yada    

```
