### ISSUE TITLE
[Question] 通过commit 自动关闭issue时如何添加一个label？

### ISSUE THREAD

**Issue by lijinke666** [actions-cool/issues-helper#64]
### 🧐 问题描述 Problem Description

比如用户提了一个issue, 是一个bug，我现在提交了一个commit修复了
 commit 消息为 `fix: xx close #xxx`, 我想在自动关闭 issue时, 自动添加一个 label `ready release`, 并自动提交一个comment，目前，借助 issue-helper create-comment 的能力，已经可以实现添加label 自动评论

我看了下 github action 的[文档](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)，似乎只有 issue closed 的钩子，无法做到 当某某用户关闭issue，或是 commit message 是 “fix：xx close #xxx” 关闭这种更细一点的

问题：如何将 commit 自动关闭所关联issue -> 添加label  这个流程走通？目前已有的功能支持吗？还是说要加代码，用github的api去获取

### 💻 示例代码 Sample code

```
name: Issue Ready Release

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready release'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}，这个bug/feature 已经修复/完成, 会在下个版本一起发布。

      - name: Remove labels
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'remove-labels,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Progress,help wanted'

```

### 🚑 其他信息 Other information

![image](https://user-images.githubusercontent.com/21015895/111340406-8dba5900-86b3-11eb-9c8c-7b4bb613892e.png)
