### ISSUE TITLE
[Question] Is it possible to keep the order of multiple actions in one step ?

### ISSUE THREAD

**Issue by meteorlxy** [actions-cool/issues-helper#78]
### 🧐 问题描述 Problem Description

The `actions` option allows multiple actions separated by comma. I found that the order of execution of the actions is not guaranteed.

However, the order of those actions could be important in some cases. For example, if I want to close and then lock an issue, I might configure like this:

```yaml
      - uses: actions-cool/issues-helper@v2.3.1
        with:
          actions: 'close-issue, lock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. This issue is marked as `invalid` and closed. Please follow the issue template.
```

The issue was firstly locked, and then closed, causing that the bot could not leave a comment to a locked issue:

![image](https://user-images.githubusercontent.com/18205362/129170633-6a09e35d-8d9e-4214-a1e4-c264f0db8028.png)

---

So maybe we could:

- Add an extra option like `parallel: false`
- Or, add a suggestion in docs, tell users to use multiple steps in such cases?
